
on:
  push:
    branches: [ main ]

name: upload-ECR-dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nextjs-test
        IMAGE_TAG: latest
      run: |
        docker build -t public.ecr.aws/o6c6k1c5/nextjs-test:latest .
        docker push public.ecr.aws/o6c6k1c5/nextjs-test:latest